import { PrismaClient, FieldValueType } from '@prisma/client';

const prisma = new PrismaClient();

// Workers Compensation Field Definitions
// All fields include: businessDescription, extractorLogic, whereToLook, inAcord130, whereInAcord130
const fieldUpdates = [
  // A. SUBMISSION & ADMINISTRATIVE
  {
    fieldName: 'applicantName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Legal name of the business entity seeking workers comp coverage.',
    extractorLogic: 'From the submission email subject and first paragraph, capture the company name in patterns like "WC submission – ABC Manufacturing, Inc.", "Workers comp quote for XYZ Plumbing LLC", "Insured: Smith Roofing Company". If ambiguous, cross-check against payroll reports, loss runs, or prior policy dec pages, which typically show the insured name in a header or "Named Insured" field. When multiple names appear (parent + DBA), choose the one paired with FEIN or "Named Insured" on prior policies; store DBAs separately if needed.',
    whereToLook: 'Submission email (subject + opening lines), broker cover letter, payroll reports, loss runs, prior policy declarations, any attached application/questionnaire.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – top right field labeled "APPLICANT NAME".',
  },
  {
    fieldName: 'mailingAddress',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Primary mailing address for the insured; official correspondence address.',
    extractorLogic: 'Search email and attachments for a full address pattern: street number + street name + city + state abbreviation + ZIP (e.g., "123 Main St, Tacoma, WA 98422"). Prioritize: address under the insured\'s name in broker cover letter or questionnaire, address labeled "Mailing Address" or "Headquarters", address labeled "Named Insured address" on prior policies or loss runs. If multiple addresses (HQ vs. job sites), choose one explicitly tied to the legal entity (not a project site).',
    whereToLook: 'Submission email signature, broker narrative, attached "WC application" PDFs, prior dec pages, loss runs headers, payroll reports.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – in the Applicant block, labeled "MAILING ADDRESS (including ZIP + 4 or Canadian Postal Code)".',
  },
  {
    fieldName: 'officePhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Main business phone number of the insured.',
    extractorLogic: 'Parse the insured/contact info block in attached questionnaires or broker cover letters; look for "Phone", "Tel", or "Office". In the email signature, identify the number closest to the insured\'s contact name, preferring labels like "Office" over "Mobile/Cell". Normalize to E.164 or (XXX) XXX-XXXX while preserving extensions (e.g., x204).',
    whereToLook: 'Submission email signature, any "WC Application" PDF/Word, contact info sections of payroll or HR rosters.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "OFFICE PHONE".',
  },
  {
    fieldName: 'mobilePhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Mobile phone of the primary insured contact.',
    extractorLogic: 'In email signature blocks, capture numbers labeled "Cell", "Mobile", "C:", or that follow the contact\'s name. If multiple numbers exist, heuristically assign the one labeled "C/Mobile" here and another as officePhone. Keep formatting similar to officePhone.',
    whereToLook: 'Submission email signature, any "Contact Sheet" attachment.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "MOBILE PHONE".',
  },
  {
    fieldName: 'website',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Official website of the insured business.',
    extractorLogic: 'Parse email signature and headers in questionnaires for http(s):// or www. links. Exclude social media; pick the primary corporate domain, ideally the same as the applicant email domain. Strip trailing slashes and paths; store root domain where possible.',
    whereToLook: 'Email signature, "About the company" paragraphs in broker submission, any marketing one-pager attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "WEBSITE ADDRESS".',
  },
  {
    fieldName: 'yearsInBusiness',
    category: 'Submission & Administrative',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Number of years the business has operated (under current or predecessor ownership).',
    extractorLogic: 'Look in questionnaires / broker application docs for fields like "Years in business", "Year established", "Business started (YYYY)". If a start year (e.g., 2012) is given, compute years-in-business relative to current policy effective year (but also store the start year separately if you want). If multiple values (e.g., "20 years in construction, 5 years as XYZ LLC"), prefer the current operation under this entity.',
    whereToLook: 'Attached WC app/questionnaire, broker email narrative ("client has been in business for 8 years"), any company profile PDF.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "YRS IN BUS".',
  },
  {
    fieldName: 'fein',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Federal Employer Identification Number (9-digit tax ID) for the insured.',
    extractorLogic: 'Scan questionnaires and payroll reports for labels: "FEIN", "Federal Tax ID", "EIN". Use a regex for 9 digits, optionally with a dash (NN-NNNNNNN or NNNNNNNNN). Verify the number appears near the applicantName to avoid grabbing someone else\'s ID (e.g., agent\'s FEIN).',
    whereToLook: 'WC application/forms, payroll summaries, experience mod worksheets, loss runs headers.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – row with "FEDERAL EMPLOYER ID NUMBER".',
  },
  {
    fieldName: 'ncciRiskId',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'NCCI-assigned Risk ID used for experience rating and WC data.',
    extractorLogic: 'In experience rating worksheets (NCCI/WCIRB, usually PDF), find "Risk ID" or "Risk Number" near the top header. Extract the alphanumeric ID exactly as shown. If absent there, check broker\'s submission email for "NCCI Risk ID".',
    whereToLook: 'NCCI/WCIRB experience mod worksheets, broker/actuary loss analysis reports, submission email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – field labeled "NCCI RISK ID NUMBER".',
  },
  {
    fieldName: 'otherEmployerRegistrationNumber',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Any state or other rating bureau employer registration number (e.g., state unemployment, state employer account number).',
    extractorLogic: 'Search questionnaires and payroll reports for text like "State Employer ID", "UI Account No.", "State Tax ID". Associate the ID with a specific state if indicated. If multiple states are listed, you can store as list of {state, registrationNumber}.',
    whereToLook: 'WC questionnaires, state registration letters attached, payroll summaries.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – field labeled "OTHER RATING BUREAU ID OR STATE EMPLOYER REGISTRATION NUMBER".',
  },
  {
    fieldName: 'submissionType',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Type of transaction requested: quote only, bind/issue, or assigned risk/other special handling.',
    extractorLogic: 'From the email subject/body, detect intent: "Please quote" / "Quote request" → quote, "Please bind", "Bind effective", "Issue policy" → issue, "Assigned risk" or "State fund only" → assigned_risk. If unclear, default to quote for new business, unless the email explicitly mentions renewal binding.',
    whereToLook: 'Submission email subject, first 1–2 paragraphs, any attached "Submission Coversheet".',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "STATUS OF SUBMISSION" section with options "QUOTE", "ISSUE POLICY", "ASSIGNED RISK (attach ACORD 133)".',
  },
  {
    fieldName: 'agencyName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Name of the broker/agency submitting the risk.',
    extractorLogic: 'Use the email sender\'s signature; capture the organization line under their name (e.g., "ABC Insurance Services"). If unclear, parse the sender\'s email domain (@abcinsurance.com) and resolve to a readable form ("ABC Insurance"). If a coversheet or proposal template is attached, use the agency name in its header.',
    whereToLook: 'Email signature, cover letters, broker-branded templates.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – top left block "AGENCY NAME AND ADDRESS".',
  },
  {
    fieldName: 'agencyAddress',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Mailing address of the submitting agency.',
    extractorLogic: 'From the email signature, collect street + city + state + ZIP that appear immediately beneath the agency name. If not in email, check any broker letterhead or PDF footer.',
    whereToLook: 'Email signatures, agency-branded documents.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – in the "AGENCY NAME AND ADDRESS" block.',
  },
  {
    fieldName: 'producerName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Primary producer/agent managing the account at the agency.',
    extractorLogic: 'From the email, take the From: display name and full name in the signature ("Jane Doe, Producer"). If multiple people are CC\'d, pick the one whose title includes "Producer", "AE/Account Executive", or "Broker".',
    whereToLook: 'Email headers, signatures, any "Producer:" line in coversheets.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PRODUCER NAME" in agency info block.',
  },
  {
    fieldName: 'csrName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Account manager/CSR supporting the producer.',
    extractorLogic: 'In email CC list and signatures, look for titles such as "Account Manager", "CSR", "Account Associate". If the sender is clearly the CSR and references "on behalf of [Producer]", record both.',
    whereToLook: 'Email CC + signature, submission coversheet.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "CSR / REPRESENTATIVE NAME".',
  },
  {
    fieldName: 'producerEmail',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Email address of the main producer contact.',
    extractorLogic: 'Use the From: email address of the submission if the sender is the producer; otherwise use the address in the signature line associated with the producer\'s name. Normalize to lowercase.',
    whereToLook: 'Email headers and signature.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'If present, in agency contact fields on Page 1; not always explicitly labeled.',
  },
  {
    fieldName: 'producerPhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Direct phone number for producer.',
    extractorLogic: 'In the producer\'s signature, capture the number labeled with their name or labeled "Direct". If only one number is present, it can be used for both officePhone and producerPhone if you want.',
    whereToLook: 'Email signature, broker contact sheets.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'Page 1 agency block if separate phone fields per contact are filled.',
  },
  {
    fieldName: 'underwriterName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Carrier underwriter the submission is being addressed to (if specified).',
    extractorLogic: 'From the salutation of the email ("Hi Sarah,") when the domain is the carrier and the role is underwriter. Or from phrases like "Attn: John Smith – Senior WC Underwriter". Not required for quoting; treat as optional.',
    whereToLook: 'Email greeting line, any submission coversheet.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "UNDERWRITER" / "COMPANY" section.',
  },
  {
    fieldName: 'agencyCustomerId',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Internal account identifier used in the agency\'s system.',
    extractorLogic: 'Look for codes labeled "Customer ID", "Client Code", "Account Number" on submission coversheets or in email subject lines (e.g., "Client ID 102345 – XYZ Construction"). Capture alphanumeric string; no standard format.',
    whereToLook: 'Coversheet PDFs, subject line, internal account snapshots attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page headers – "AGENCY CUSTOMER ID".',
  },
  {
    fieldName: 'billingPlan',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Whether the account will be agency-billed or direct-billed and any special billing instructions.',
    extractorLogic: 'Search submission cover emails and questionnaires for terms like "direct bill", "agency bill", "bill insured direct", "agency billed". Map text to canonical values agency_bill vs direct_bill. If not specified, leave null; this is often chosen by carrier or broker later.',
    whereToLook: 'Submission email, broker WC application, any "Billing Instructions" attachment.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "BILLING / AUDIT INFORMATION – BILLING PLAN (AGENCY BILL / DIRECT BILL)".',
  },
  {
    fieldName: 'paymentPlan',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Requested installment schedule (annual, quarterly, monthly reporting, etc.).',
    extractorLogic: 'Look for phrases like "quarterly installments", "monthly reporting policy", "annual pay". Map to enumeration: annual, semi_annual, quarterly, monthly, payroll_reporting.',
    whereToLook: 'Submission email, billing instruction pages, broker cover letter.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PAYMENT PLAN" checkboxes (Annual, Semi-Annual, Quarterly, etc.).',
  },
  {
    fieldName: 'auditType',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'How and when payroll audit is performed (at expiration vs. periodic self-reporting).',
    extractorLogic: 'Search for text like "annual audit", "monthly payroll reporting", "auditable at policy term". Map common phrases to at_expiration, monthly_reporting, semi_annual, etc.',
    whereToLook: 'Submission email, WC appetite/quote request docs, prior policies (audit section).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "AUDIT (AT EXPIRATION / MONTHLY / SEMI-ANNUAL)".',
  },
  // B. BUSINESS ENTITY & OPERATIONS / GENERAL INFO
  {
    fieldName: 'entityType',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Legal structure of the insured entity (e.g., individual, partnership, corporation, LLC, etc.).',
    extractorLogic: 'Parse the WC supplemental application and broker\'s cover letter for a labeled field like "Entity type", "Business type", or "Legal structure". If not explicitly filled, infer from the legal name: Names ending in "Inc." → corporation, "LLC", "L.L.C." → llc, "LP", "LLP" → partnership variants. Normalize to a small set of enumerated values: individual, partnership, corporation, s_corp, llc, trust, joint_venture, other.',
    whereToLook: 'WC supplemental or "Business information" questionnaire, Broker submission email (intro section), Prior policy dec pages (Named Insured + entity type line).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – row of checkboxes in the Applicant block labeled something like "INDIVIDUAL, PARTNERSHIP, CORPORATION, SUBCHAPTER S CORP, LLC, TRUST, JOINT VENTURE, OTHER".',
  },
  {
    fieldName: 'operationsDescription',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'text' as FieldValueType,
    businessDescription: 'Narrative description of what the business does: services performed, products, customers, and work environment.',
    extractorLogic: 'In WC supplemental and any "Operations" section, extract the full text answer to questions like "Describe your operations in detail", "What does the business do?". If not present or too short, use the submission email body (first 1–3 paragraphs where the broker explains the insured) and pull the contiguous sentences describing operations (e.g., "They operate 4 casual dining restaurants…"). Preserve full paragraph text; do not over-truncate. This field is for LLM context as well as mapping to class codes.',
    whereToLook: 'WC supplemental ("Description of operations"), Broker submission email narrative, Any attached marketing/profile one-pager.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – large narrative box typically labeled "NATURE OF BUSINESS / DESCRIPTION OF OPERATIONS".',
  },
  {
    fieldName: 'hazardousMaterialsExposure',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured\'s past, present, or discontinued operations involve storing, treating, discharging, applying, disposing, or transporting hazardous materials (chemicals, fuels, waste, etc.).',
    extractorLogic: 'In the WC supplemental, look for environmental/risk questions like "Any use, storage, or transport of hazardous materials?", "Any fuel storage tanks, chemicals, or waste handling?". Parse the Yes/No and any narrative description. If not clearly asked in a questionnaire, scan the operationsDescription and any risk engineering reports for keywords: "hazardous", "chemicals", "solvents", "fuel tanks", "waste handling", "hazmat" and infer exposure = Yes if clearly present. Store as a structured object: answer: Yes/No, details: free-text description if provided.',
    whereToLook: 'WC supplemental – "Environmental/hazardous materials" or "General info" section, Risk engineering / safety reports, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 2, typically worded: "DO/HAVE PAST, PRESENT OR DISCONTINUED OPERATIONS INVOLVE STORING, TREATING, DISCHARGING, APPLYING, DISPOSING, OR TRANSPORTING OF HAZARDOUS MATERIALS (e.g., landfills, wastes, fuel tanks, etc.)?" with Yes/No checkboxes and a remarks area.',
  },
  {
    fieldName: 'aircraftOrWatercraftOwned',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured owns, operates, or leases aircraft or watercraft as part of its operations.',
    extractorLogic: 'Look for a general info table in the WC supplemental with questions like "Any owned, leased, or chartered aircraft or watercraft?"; capture Yes/No and explanation. If no explicit question, scan operations and fleet descriptions for words like "plane", "helicopter", "vessel", "boat", "barge", "tug", "charter". Default to No if not mentioned and industry is unlikely to have such exposures (e.g., small restaurant, office-only), but better to leave null if ambiguous.',
    whereToLook: 'WC supplemental – General Information / Exposures section, Fleet or auto schedules (sometimes list watercraft), Broker email if they call out aircraft/watercraft exposures.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 1, usually: "DOES APPLICANT OWN, OPERATE OR LEASE AIRCRAFT/WATERCRAFT?" (Yes/No + explanation).',
  },
  {
    fieldName: 'workUndergroundOrAbove15Feet',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether employees perform work underground or above 15 feet (e.g., trenching, high scaffolding, elevated roofing), which materially changes risk severity.',
    extractorLogic: 'Find questions in the WC supplemental such as "Any work above 15 feet?", "Any underground work or trenching?". Extract Yes/No; parse the explanation field for height ranges and % of work ("framing work up to 20 ft, about 30% of jobs"). If not explicitly asked, scan operationsDescription for terms like "roofing", "scaffolding", "elevated platforms", "trenching", "shoring" and infer high-level yes/no with details.',
    whereToLook: 'WC supplemental – "Operations exposure" or "Work height/underground" questions, Safety/risk questionnaire, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 3: "ANY WORK PERFORMED UNDERGROUND OR ABOVE 15 FEET?" (Yes/No + explanation).',
  },
  {
    fieldName: 'workOverWater',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any work is performed on barges, vessels, docks, piers, or bridges over water.',
    extractorLogic: 'Look for yes/no questions about marine exposures in the WC supplemental ("Any work on or over water?"). If "Yes", extract details such as type of structure (docks, barges), typical duration, % of overall work, and locations. If not asked, search the operations narrative for "dock", "pier", "barge", "marine", "over water", "bridge" and derive.',
    whereToLook: 'WC supplemental – General exposures section, Marine/contractor addenda if present, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 4: "ANY WORK PERFORMED ON BARGES, VESSELS, DOCKS, BRIDGES OVER WATER?".',
  },
  {
    fieldName: 'subcontractorUsage',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether the insured uses subcontractors to perform part of the work.',
    extractorLogic: 'In the WC supplemental, find the line "Subcontractors used?" Yes/No. Capture the Yes/No answer and treat as subcontractorUsage. If no explicit field but operations clearly include subbing (e.g., GC describing subs), infer Yes and capture note in details.',
    whereToLook: 'WC supplemental – "Subcontractor usage" section, Broker email describing operations ("we sub out electrical and plumbing"), Any attached subcontractor procedures/COI language.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 6: "ARE SUB-CONTRACTORS USED? (If \'YES\', give % of work subcontracted)".',
  },
  {
    fieldName: 'subcontractorPercentageSubcontracted',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Approximate percentage of total work or revenue subcontracted to others.',
    extractorLogic: 'Next to the "Subcontractors used?" Yes/No in the WC supplemental, capture numeric values like "20%", "1/3 of work", "about half of field work". Normalize textual fractions into approximate percentages (e.g., "one third" → 33). If no precise figure, infer from narrative if clearly stated ("most specialized trades are subbed out" could be approximated as >50%, or left as null with narrative only).',
    whereToLook: 'WC supplemental – same section as subcontractor usage, Broker email ("~20% of work subbed to licensed trades").',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – same General Information Question 6 remarks line: insurer expects "% of work subcontracted" if "Yes" is checked.',
  },
  {
    fieldName: 'workSubletWithoutCOI',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any work is sublet to subcontractors who do not provide certificates of insurance (COIs) for WC and GL.',
    extractorLogic: 'In the WC supplemental, find questions like "Any work sublet without COIs?" or "Do you always obtain certificates of insurance from subcontractors?". Extract Yes/No and narrative ("Occasionally use small subs without COIs, less than 5% of work"). If the supplement only says "COIs required for all subs", infer workSubletWithoutCOI = No.',
    whereToLook: 'WC supplemental – subcontractor & COI section, Broker email describing subcontractor management.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 7: "ANY WORK SUBLET WITHOUT CERTIFICATES OF INSURANCE? (If \'YES\', payroll for this work must be included in the State Rating Worksheet on Page 2.)".',
  },
  {
    fieldName: 'otherBusinessOperations',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'text' as FieldValueType,
    businessDescription: 'Other types of business activities conducted by the insured beyond the main operations (e.g., retail, manufacturing, distribution side lines).',
    extractorLogic: 'In WC supplemental, look for a question explicitly asking if there are other operations or divisions; capture Yes/No and full explanation. In operationsDescription, detect structure like "In addition to X, they also operate Y…" and capture the "also operate" part as otherBusinessOperations. Store as free text; downstream, it can be used to drive additional class codes.',
    whereToLook: 'WC supplemental – "Other operations / side businesses" question, Operations narrative (broker email or attachment).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 5: "IS APPLICANT ENGAGED IN ANY OTHER TYPE OF BUSINESS?" (with explanation field).',
  },
  {
    fieldName: 'safetyProgramInOperation',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether there is a formal written safety program in place (policies, training, documented procedures).',
    extractorLogic: 'In the WC supplemental safety section, find "Written safety program?" or "Formal safety program?"; capture Yes/No and any notes ("OSHA-compliant written program, updated annually"). If they attach a Safety Manual or reference "see attached safety program", set answer to Yes and note attachments. If completely silent and high-risk industry, leave null instead of assuming No.',
    whereToLook: 'WC supplemental – safety & loss control section, Any attached safety manual or policy summary, Broker cover letter (often highlighting safety program as a positive).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 8: "IS A WRITTEN SAFETY PROGRAM IN OPERATION?".',
  },
  {
    fieldName: 'groupTransportationProvided',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer provides transportation for groups of employees (e.g., vans, buses, crew trucks) to job sites.',
    extractorLogic: 'In the WC supplemental, look for "Do you provide group transportation to employees?" or similar. Extract Yes/No plus description of vehicles and usage if given. Scan operationsDescription for "crew vans", "company shuttle", "transport crews to sites" and infer as needed.',
    whereToLook: 'WC supplemental – transportation or fleet exposures section, Fleet / auto supplement (if attached), Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 9: "ANY GROUP TRANSPORTATION PROVIDED?".',
  },
  {
    fieldName: 'employeesUnder16OrOver60',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any employees are younger than 16 or older than 60, used as a risk screening factor.',
    extractorLogic: 'On the WC supplemental, capture Yes/No to any question about "employees under 16 or over 60". From any employee age distribution reports (if attached), infer yes if extremes are present. Where counts are given ("3 employees over 60"), store them optionally alongside the Yes.',
    whereToLook: 'WC supplemental – employee demographics section, HR/employee summary reports (if included).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 10: "ANY EMPLOYEES UNDER 16 OR OVER 60 YEARS OF AGE?".',
  },
  {
    fieldName: 'seasonalEmployees',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured uses seasonal workers (e.g., during summer, harvest, holiday season).',
    extractorLogic: 'Identify the yes/no question in supplemental for "seasonal employees"; capture answer and, if available, typical season and headcount. If payroll schedules show large seasonal spikes (e.g., Q4 payroll much higher with note "seasonal staff"), mark as Yes and capture the description.',
    whereToLook: 'WC supplemental – employee profile section, Payroll by quarter or seasonal payroll attachments.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 11: "ANY SEASONAL EMPLOYEES?".',
  },
  {
    fieldName: 'volunteerOrDonatedLabor',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Use of workers who are not paid employees but volunteer or provide donated labor.',
    extractorLogic: 'Find the volunteer labor question in the supplemental and capture Yes/No plus description ("church volunteers help staff the thrift store on weekends"). If the insured is a non-profit where volunteers are likely, but the form is silent, leave null (don\'t assume).',
    whereToLook: 'WC supplemental – general info section, Nonprofit-specific supplements, if attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 12: "IS THERE ANY VOLUNTEER OR DONATED LABOR? (If \'YES\', please specify)".',
  },
  {
    fieldName: 'employeesWithPhysicalHandicaps',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any employees with physical handicaps are employed, which may be a consideration for underwriting.',
    extractorLogic: 'Capture Yes/No from the specific question on the WC supplemental; often answered "No". Do not attempt to infer from other data (avoid making assumptions about disabilities).',
    whereToLook: 'WC supplemental – general info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 13: "ANY EMPLOYEES WITH PHYSICAL HANDICAPS?".',
  },
  {
    fieldName: 'employeesTravelOutOfState',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether employees travel outside the main state of operation, including which states and how often.',
    extractorLogic: 'In the supplemental, extract Yes/No and parse the text field for state abbreviations and frequency qualifiers ("OR and ID weekly; CA quarterly"). Where not explicitly listed, search operationsDescription and cover letter for cross-border work ("crews regularly cross from WA into OR"). Store as structured list if possible: [{"state": "OR", "frequency": "weekly"}, ...].',
    whereToLook: 'WC supplemental – travel/out-of-state question, Broker email describing multi-state operations, Payroll by state (corroborate which states have employees).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 14: "DO EMPLOYEES TRAVEL OUT OF STATE? (If \'YES\', indicate state(s) of travel and frequency)".',
  },
  {
    fieldName: 'athleticTeamsSponsored',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer sponsors athletic teams (e.g., company softball or soccer teams), creating incidental WC exposure.',
    extractorLogic: 'Capture Yes/No from a supplemental question on "Athletic teams sponsored?". If Yes, extract name/type of team and whether participants are employees.',
    whereToLook: 'WC supplemental – general info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 15: "ARE ATHLETIC TEAMS SPONSORED?".',
  },
  {
    fieldName: 'preEmploymentPhysicalsRequired',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether physical exams are required after offers of employment are made.',
    extractorLogic: 'From supplemental, read Yes/No on "Pre-employment physicals required?". If details are given ("required for all drivers and warehouse staff"), capture as free text.',
    whereToLook: 'WC supplemental – hiring/HR practices section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 16: "ARE PHYSICALS REQUIRED AFTER OFFERS OF EMPLOYMENT ARE MADE?".',
  },
  {
    fieldName: 'otherInsuranceWithThisInsurer',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured has other policies (e.g., GL, auto, property) with the same carrier considering this WC quote.',
    extractorLogic: 'On the supplemental, look for a question about "Any other policies with this carrier?" or "Do you currently have policies with us?". If the broker email explicitly says "They already place GL and Auto with you", set to Yes and capture lines of business.',
    whereToLook: 'WC supplemental – general info section, Broker cover letter (cross-sell pitch).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 17: "ANY OTHER INSURANCE WITH THIS INSURER?".',
  },
  {
    fieldName: 'priorCoverageDeclinedOrCancelled',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether prior workers comp coverage has been declined, cancelled, or non-renewed within the recent past (usually 3 years).',
    extractorLogic: 'Read Yes/No from the relevant question on the WC supplemental; if Yes, capture full explanation including carrier, date, and reason. If broker email mentions "non-renewed due to loss ratio" or "previous carrier declined renewal", capture that.',
    whereToLook: 'WC supplemental – prior coverage section, Broker email narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 18: "ANY PRIOR COVERAGE DECLINED / CANCELLED / NON-RENEWED IN THE LAST THREE (3) YEARS?" (with state-specific instructions).',
  },
  {
    fieldName: 'employeeHealthPlansProvided',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer provides health insurance plans to employees (group medical).',
    extractorLogic: 'On the supplemental, capture Yes/No and any notes on the type of plan ("group health, 70% employer paid"). Do not try to infer from industry; if not mentioned, leave null.',
    whereToLook: 'WC supplemental – benefits/employee info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 19: "ARE EMPLOYEE HEALTH PLANS PROVIDED?".',
  },
  {
    fieldName: 'leasedEmployees',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured leases employees to or from another entity (PEO or staff leasing arrangement).',
    extractorLogic: 'Find the leased employees question in the supplemental; record Yes/No and any vendor names (e.g., "PEO: Trinet"). If there is a separate PEO/leased employee addendum attached, you can set this to Yes even if the main form says nothing.',
    whereToLook: 'WC supplemental – leased employees/PEO section, Any attached PEO agreement or schedule.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 21: "DO YOU LEASE EMPLOYEES TO OR FROM OTHER EMPLOYERS?".',
  },
  {
    fieldName: 'employeesWorkingAtHome',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether employees predominantly work from home and how many.',
    extractorLogic: 'From the supplemental, capture Yes/No and numeric count if provided ("4 admin employees working remotely"). If no explicit question but an employee roster or org chart indicates remote roles ("Remote account manager"), you can capture approximate counts.',
    whereToLook: 'WC supplemental – general info/employee section, Employee roster (if attached).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 22: "DO ANY EMPLOYEES PREDOMINANTLY WORK AT HOME? (If \'YES\', # OF EMPLOYEES: ___)".',
  },
  {
    fieldName: 'taxLiensOrBankruptcyLast5Years',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured has had any tax liens or bankruptcy within the last five years.',
    extractorLogic: 'Extract Yes/No from the financial history question in the supplemental. If Yes, capture the narrative including dates, type (tax lien vs bankruptcy), and current status ("Chapter 11 discharged 2023").',
    whereToLook: 'WC supplemental – financial/ownership section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 23: "ANY TAX LIENS OR BANKRUPTCY WITHIN THE LAST FIVE (5) YEARS? (If \'YES\', please specify)".',
  },
  {
    fieldName: 'unpaidWCPremiumLast5Years',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether there is any undisputed, unpaid workers comp premium due from the insured or commonly managed/owned enterprises.',
    extractorLogic: 'Read Yes/No from the corresponding question in the WC supplemental. If Yes, extract details: entities, carriers, approximate amounts, and policy numbers.',
    whereToLook: 'WC supplemental – financial/prior premium section, Broker may occasionally mention this in email if it affects placement.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 24: "ANY UNDISPUTED AND UNPAID WORKERS COMPENSATION PREMIUM DUE FROM YOU OR ANY COMMONLY MANAGED OR OWNED ENTERPRISES? IF YES, EXPLAIN INCLUDING ENTITY NAME(S) AND POLICY NUMBER(S).".',
  },
  // C. LOCATIONS (Array fields - each location has these fields)
  {
    fieldName: 'locationNumber',
    category: 'Locations',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'A simple index (Loc #) that uniquely identifies each insured location within the account. Used to tie addresses, class codes, and payroll together.',
    extractorLogic: 'Anchor from how the broker presents locations, not from ACORD: In WC supplemental or submission email, look for bullets/tables like "Location 1 – 123 Main St …", "Loc 1 (HQ)… Loc 2 (Warehouse)…". If explicit "Location #" labels exist, reuse those numeric IDs. If locations are only described by addresses with no explicit numbers, assign a deterministic index in reading order: First distinct address → locationNumber = 1, second → 2, etc. Ensure you reuse the same index across other tables (class codes, payroll) by matching on address/state.',
    whereToLook: 'WC supplemental – "Locations" or "Premises" section, Submission email (often a bullet list of locations), Payroll by state/class workbook (tabs or columns may reference location names/IDs), Loss runs and prior policies sometimes repeat location labels.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "LOCATIONS" section, first column labeled "LOC #" in the locations grid.',
  },
  {
    fieldName: 'locationStreetAddress',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'The street line for the physical location (e.g., "4100 Marine View Drive").',
    extractorLogic: 'For each location, parse the first line of any address block in supplemental or email for that site: Patterns like ^\\d+\\s+.* (street number + name). If address is in a single line ("123 Main St, Springfield, IL 62701"), split on commas and treat the first element as locationStreetAddress. Handle multiple-line formats (suite/floor): keep only the primary street line here, store suite/floor separately if needed.',
    whereToLook: 'WC supplemental – location/address table, Submission email – location bullets ("Location 1: 4100 Marine View Drive, Tacoma, WA…"), Payroll spreadsheets – location or "worksite address" columns, Loss runs – "Loss Location" header for each claim.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "LOCATIONS" grid, column labeled "STREET, CITY, COUNTY, STATE, ZIP CODE"; street is the first line of that cell.',
  },
  {
    fieldName: 'locationCity',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'City where the insured location is physically situated.',
    extractorLogic: 'Parse the full address string and identify the city as the component immediately before the state abbreviation: Example: "4100 Marine View Drive, Tacoma, WA 98422" → city = Tacoma. Use a US city + state pattern or a small city dictionary to avoid mis-parsing long street names.',
    whereToLook: 'WC supplemental – address fields, Submission email – narrative or bullet location list, Payroll or HR reports – "City" column.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – same "STREET, CITY, COUNTY, STATE, ZIP CODE" column; city is the second component of the address line.',
  },
  {
    fieldName: 'locationCounty',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'County of the physical location, used in some states for jurisdiction and rating.',
    extractorLogic: 'If the county is explicitly listed in the supplemental ("County: Pierce") or address line ("Tacoma, Pierce County, WA 98422"), capture it as text. If not provided in documents, you can: Either leave locationCounty empty, or If you have an internal geocoding service in Autos later, map city+ZIP to county—but do not hallucinate one here from LLM alone. Don\'t try to infer county from carrier domain or anything non-address.',
    whereToLook: 'WC supplemental – location details tables (often have "County" column), Prior policies – sometimes list county with each location, Engineering/risk inspection reports.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – within the same "STREET, CITY, COUNTY, STATE, ZIP CODE" field, county often appears on the line or in parentheses.',
  },
  {
    fieldName: 'locationState',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Two-letter state or jurisdiction where the location is physically located (e.g., WA, CA, TX).',
    extractorLogic: 'Parse addresses and capture the two-letter state code from patterns like [A-Z]{2} \\d{5}. Normalize to uppercase and validate against US state list (or include CAN provinces if relevant). This locationState must align with the WC rating state (used later for wcState and class code rows).',
    whereToLook: 'WC supplemental – address lines, Submission email – location list, Payroll by state/class – state column (cross-check), Loss runs – "Loss Location" lines.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "STREET, CITY, COUNTY, STATE, ZIP CODE" field; state is the standard two-letter abbreviation preceding ZIP.',
  },
  {
    fieldName: 'locationZip',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: '5-digit (and optionally +4) ZIP/postal code of the location.',
    extractorLogic: 'From each address, capture ZIP with regex: \\d{5} or \\d{5}-\\d{4} at the end of the address. Store locationZip as the 5-digit base (optionally store +4 in a separate field if you add one). If multiple ZIPs appear in same block (rare), prioritize the one nearest the state abbreviation.',
    whereToLook: 'WC supplemental – address fields, Submission email – location list, Payroll/HR spreadsheets – ZIP or postal code columns.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – in the "STREET, CITY, COUNTY, STATE, ZIP CODE" column; last part of address.',
  },
  {
    fieldName: 'locationFloor',
    category: 'Locations',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Floor or level within a building where the operation occurs (if relevant) – e.g., "3rd Floor", "Basement".',
    extractorLogic: 'Look for floor indicators embedded in the address lines in supplemental/email: "3rd Floor", "4th Fl", "B1 Level", "Ground Floor", "Mezzanine". Use regex on address strings to strip patterns like (\\d+(st|nd|rd|th)\\s+Floor|Fl) or words "Basement", "Mezzanine". Store as a short, normalized string (e.g., "3rd Floor", "Basement"). If no floor info is present, leave null (do not assume "Ground Floor").',
    whereToLook: 'WC supplemental – address / premises details, Submission email – sometimes used for office-only exposures ("HQ – 7th floor office in tower"), Lease/tenant schedules or floor plans if attached.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'Page 1 – within the location address lines in the "STREET, CITY, COUNTY, STATE, ZIP CODE" field (e.g., "Suite 400, 4th Floor").',
  },
  // D. CLASSIFICATION / PAYROLL / RATING (Per State & Class Code) - Array fields
  {
    fieldName: 'wcState',
    category: 'Classification / Payroll / Rating',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'The state for which the payroll and class code apply (jurisdiction for rating).',
    extractorLogic: 'Parse the "Payroll by Class & State" Excel file: capture the State column exactly as written (WA, OR, CA). If missing there, derive from locationState associated with the payroll/class row. Validate as two-letter code.',
    whereToLook: 'Payroll by Class & State (Excel), WC supplemental — sometimes states listed under "States of operation", Submission email summary.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – "STATE RATING WORKSHEET" rows, column labeled STATE.',
  },
  {
    fieldName: 'ratingLocationNumber',
    category: 'Classification / Payroll / Rating',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'The location number tied to the payroll/class row. Aligns to your locations[] indices.',
    extractorLogic: 'Use location number from the payroll Excel column if provided ("Location 1, 2…"). If not present, match the payroll row\'s address/state to the locations[] entries created in Batch C and assign the matching locationNumber. If multiple states share a single HQ address, the supplemental will indicate which location corresponds to which state exposure.',
    whereToLook: 'Payroll Excel workbook, WC supplemental — location table, Submission email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, LOC # column.',
  },
  {
    fieldName: 'classCode',
    category: 'Classification / Payroll / Rating',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'The NCCI (or state-specific) classification code for the work performed (e.g., 5403, 8810).',
    extractorLogic: 'From payroll Excel: take the numeric class code exactly. If multiple class codes are referenced in supplemental ("frame carpentry 5403; roofing 5551; clerical 8810"), map each to its payroll row. Validate numeric-only unless a monopolistic state uses a variant (e.g., WA class codes differ — but still numeric).',
    whereToLook: 'Payroll Excel, WC supplemental — "Operations/Classifications" section, Broker email (often lists primary codes for quick quote).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, CLASS CODE column.',
  },
  {
    fieldName: 'classCodeDescription',
    category: 'Classification / Payroll / Rating',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'The narrative description associated with the class code (e.g., "Carpentry NOC", "Clerical Office").',
    extractorLogic: 'Pull directly from the payroll Excel\'s "Description" column. If missing, extract from WC supplemental ("Primary classification: clerical, carpentry, sales"). Optional: Cross-reference NCCI description to standardize wording, but do not hallucinate new descriptions.',
    whereToLook: 'Payroll Excel, WC supplemental — "Description of operations / class codes", Submission email (producer often summarizes these).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, CLASSIFICATION DESCRIPTION column.',
  },
  {
    fieldName: 'dutiesDescription',
    category: 'Classification / Payroll / Rating',
    fieldType: 'text' as FieldValueType,
    businessDescription: 'More detailed description of what employees in this class code actually do (e.g., "framing, setting trusses, light roofing").',
    extractorLogic: 'For each class code row, extract relevant sentences from operationsDescription that mention specific duties related to that class: Example: If classCode = 5403, pull sentences about carpentry/framing. If the payroll Excel has a "Duties" column, use that verbatim. Never infer duties not mentioned in docs; only reuse text the insured provides.',
    whereToLook: 'WC supplemental — detailed operations section, Payroll Excel — sometimes includes "Job duties", Submission email narrative.',
    inAcord130: 'No',
    whereInAcord130: 'No dedicated field, but it often appears in Page 3 "NATURE OF BUSINESS / DESCRIPTION OF OPERATIONS" remarks or in Page 2 "REMARKS" for class specifics.',
  },
  {
    fieldName: 'numEmployeesFullTime',
    category: 'Classification / Payroll / Rating',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Number of full-time employees assigned to the class code.',
    extractorLogic: 'Pull from payroll Excel if a column exists ("FT Employees"). If not given explicitly: Use employee roster summary if available, Match job titles to class codes: e.g., "14 framers" → FT for 5403. If only total headcount is given and no FT/PT split, set this field to null rather than guessing.',
    whereToLook: 'Payroll Excel, Employee roster CSV, WC supplemental ("# of FT employees by role").',
    inAcord130: 'No',
    whereInAcord130: 'Could be placed in Page 2 "REMARKS" for rating context but not a structured ACORD field.',
  },
  {
    fieldName: 'numEmployeesPartTime',
    category: 'Classification / Payroll / Rating',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Number of part-time or seasonal workers for the class code.',
    extractorLogic: 'Pull directly from payroll Excel if "PT Employees" exists. If seasonal workers are called out ("9 seasonal workers"), map workers performing that job type to the correct class code row. If only aggregate seasonal count is given and cannot be matched to specific class codes, leave null.',
    whereToLook: 'Payroll Excel, WC supplemental — "seasonal employees" section, Employee roster.',
    inAcord130: 'No',
    whereInAcord130: 'Same as FT employees — Page 2 remarks if carrier needs details.',
  },
  {
    fieldName: 'estimatedAnnualPayroll',
    category: 'Classification / Payroll / Rating',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Estimated payroll for the next policy year for employees under this class code and state.',
    extractorLogic: 'From payroll Excel: take the column "Est Annual Payroll" exactly. If not present in Excel but given in supplemental ("2026 estimated payroll for carpentry: $2.45M WA, $850k OR"), construct rows for each state/class. Normalize formatting (strip "$", commas).',
    whereToLook: 'Payroll Excel, WC supplemental — "Payroll by class/state" table, Submission email sometimes summarizes these numbers.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, ESTIMATED ANNUAL PAYROLL column.',
  },
  {
    fieldName: 'rate',
    category: 'Classification / Payroll / Rating',
    fieldType: 'decimal' as FieldValueType,
    businessDescription: 'The manual WC rate (per $100 payroll) applied to the class code for the given state.',
    extractorLogic: 'Extract from payroll Excel if a "Rate" column exists. If not provided, leave null; carriers fill this during rating. Do not calculate rates or infer from industry; must be from documents or left blank.',
    whereToLook: 'Payroll Excel, Rarely in WC supplemental, Never infer from loss runs.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, RATE column.',
  },
  {
    fieldName: 'estimatedAnnualManualPremium',
    category: 'Classification / Payroll / Rating',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'The product of estimated payroll × manual rate (per $100), before experience mod, schedule credits, taxes, and fees.',
    extractorLogic: 'If the payroll Excel already includes a premium column, use that value exactly. If not included but rate + payroll are known: Autos can calculate this safely as: manual premium = (estimatedAnnualPayroll / 100) × rate. Round to nearest whole dollar unless documents specify other rounding. If rate is missing, leave premium null.',
    whereToLook: 'Payroll Excel (may have formula-driven premium), WC supplemental (some brokers list estimated premium per class).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET, ESTIMATED ANNUAL PREMIUM column.',
  },
  // E. COVERAGES & LIMITS
  {
    fieldName: 'coveredStatesPart1',
    category: 'Coverages & Limits',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'The specific states in which the insured is requesting Statutory Workers Compensation coverage under Part One.',
    extractorLogic: 'Parse the WC supplemental\'s "States of Operation / Covered States" section for the primary states where employees work. If the submission email explicitly states ("They operate in WA and OR"), record those as covered states. Cross-check with payroll Excel to ensure each state with payroll is included. Store as a unique list of state codes, sorted, e.g., ["WA", "OR"].',
    whereToLook: 'WC supplemental – "Business Information" or "Operations Locations", Payroll by Class & State (Excel), Submission email summary.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 top right "COVERAGES" table—column labeled PART ONE – WORKERS COMPENSATION where state codes (e.g., "WA", "OR") are listed.',
  },
  {
    fieldName: 'otherStatesInsuranceStatesPart3',
    category: 'Coverages & Limits',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'States to be covered under Part Three — Other States Insurance (i.e., states where employees may work but the employer does not have existing operations).',
    extractorLogic: 'Identify supplemental form questions like: "Any employees travel out of state?", "List states employees may enter." For each state mentioned in out-of-state travel (Batch B field), determine if it is not already in coveredStatesPart1. Add those to otherStatesInsuranceStatesPart3, except for monopolistic states (ND, OH, WA, WY — carriers often exclude automatically). Format as an array of state codes.',
    whereToLook: 'WC supplemental – out-of-state question, Submission email (e.g., "crews cross from WA into ID weekly"), Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 "COVERAGES" section under PART THREE — OTHER STATES INSURANCE labeled "Applicable in (States)".',
  },
  {
    fieldName: 'excludedStatesPart1',
    category: 'Coverages & Limits',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'States the insured explicitly does not want covered under Part One (usually automatic in some carrier guidelines).',
    extractorLogic: 'If the supplemental has a section like: "States to exclude?", "Do not apply coverage in the following states:" capture the list. Sometimes the email says "WA only — do not include OR". Compare against payroll Excel: If payroll exists for a state, it cannot be an excluded state. Store as array of state codes.',
    whereToLook: 'WC supplemental ("Covered / excluded states" section), Submission email instructions.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 "COVERAGES" table where states can be left blank or listed under "EXCLUDED STATES". (Often shown as a separate line or remarks field.)',
  },
  {
    fieldName: 'employersLiabilityEachAccident',
    category: 'Coverages & Limits',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'The limit for Employers Liability (EL) for each accident, part of Part Two coverage.',
    extractorLogic: 'Capture from WC supplemental if a carrier limit is selected (usually $100,000 / $500,000 / $1,000,000). If broker email states "Please quote EL at $1M/$1M/$1M", map the first number to this field. If no limit is specified, carriers default to $100,000 unless requested, so leave null if absent.',
    whereToLook: 'WC supplemental – coverage limits table, Broker email ("quote with state limits and $1M EL").',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "COVERAGES" section, under PART TWO — EMPLOYERS LIABILITY, column "EACH ACCIDENT".',
  },
  {
    fieldName: 'employersLiabilityDiseasePolicyLimit',
    category: 'Coverages & Limits',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'EL limit for disease — policy limit, applying to all disease claims.',
    extractorLogic: 'Extract the middle of the typical three-part limit selection: Example: "$1,000,000 / $1,000,000 / $1,000,000" → second value. If supplemental has "EL Limits: 1M/1M/1M", parse the pattern. Store numeric value as integer dollars.',
    whereToLook: 'WC supplemental – coverage limits, Submission email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PART TWO — EMPLOYERS LIABILITY", column DISEASE — POLICY LIMIT.',
  },
  {
    fieldName: 'employersLiabilityDiseaseEachEmployee',
    category: 'Coverages & Limits',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'EL limit for disease — each employee.',
    extractorLogic: 'Parse the final number in an EL limit triplet. If listed individually in the supplemental (common in some forms), capture directly. Store as numeric.',
    whereToLook: 'WC supplemental – coverage limits, Submission email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PART TWO — EMPLOYERS LIABILITY", column DISEASE — EACH EMPLOYEE.',
  },
  {
    fieldName: 'medicalDeductible',
    category: 'Coverages & Limits',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Deductible amount applicable to medical-only WC claims.',
    extractorLogic: 'Look for deductible requests in supplemental: "Medical-only deductible: $500", "We want a $0 deductible quote as well as a $1,000 med-only deductible option." Extract the numeric amount; if multiple options are requested, store the requested value, and optionally capture alternative(s) in a secondary field.',
    whereToLook: 'WC supplemental – deductibles section, Broker email ("quote with $500 med-only deductible").',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 or Page 2 – sometimes in "DEDUCTIBLES" table or listed in "STATE RATING WORKSHEET – DEDUCTIBLE PLAN OPTION". (Your ACORD 130 shows a section near Page 1 bottom titled "DEDUCTIBLES" with options.)',
  },
  {
    fieldName: 'indemnityDeductible',
    category: 'Coverages & Limits',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Deductible applicable to indemnity portions of WC claims.',
    extractorLogic: 'Extract from supplemental if a combined deductible is requested ("$1,000 per-claim deductible"). If supplemental differentiates between med-only and indemnity, map appropriately. If not mentioned anywhere: null.',
    whereToLook: 'WC supplemental – deductibles section, Producer\'s email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Same "DEDUCTIBLES" table as medical deductible (Page 1/2).',
  },
  {
    fieldName: 'uslhCoverage',
    category: 'Coverages & Limits',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether USL&H coverage is being requested for employees working over navigable waters (docks, piers, shipyards). (USL&H = United States Longshore & Harbor Workers\' Compensation Act)',
    extractorLogic: 'Look for explicit questions in supplemental: "Any USL&H exposure?", "Any work over water?" (tie to Batch B "workOverWater"). If "workOverWater" = Yes, supplemental often requires an additional "Yes/No" on whether USL&H coverage is required. Store as boolean and include % of payroll needing USL&H if mentioned.',
    whereToLook: 'WC supplemental – marine/longshore exposure section, Submission email ("No Longshore exposure").',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – under "COVERAGES", usually a checkbox or remarks line labeled USL&H or "Longshore". Some versions place it under "STATE RATING WORKSHEET – SPECIAL COVERAGE CODES".',
  },
  {
    fieldName: 'volunteerCompCoverage',
    category: 'Coverages & Limits',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured requests Workers Compensation coverage for volunteers (WC does not automatically apply to volunteers unless specifically endorsed).',
    extractorLogic: 'Supplemental sometimes includes: "Any volunteer labor?" (Batch B) and separately asks if they want volunteers covered. If the organization is a nonprofit and states "Request volunteer WC endorsement", set this field to Yes. Store additional details if provided (number of volunteers, type of volunteer activities).',
    whereToLook: 'WC supplemental – volunteer or nonprofit section, Submission email (nonprofits often explicitly request this endorsement).',
    inAcord130: 'Yes',
    whereInAcord130: 'Usually Page 1 "COVERAGES – VOLUNTEERS" remarks line or Page 3/4 under "REMARKS". ACORD doesn\'t always have a dedicated labeled box, but this is the carrier\'s standard place.',
  },
  {
    fieldName: 'foreignCoverage',
    category: 'Coverages & Limits',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether foreign voluntary workers compensation or foreign travel WC endorsements are requested.',
    extractorLogic: 'Look for fields in supplemental: "Any employees traveling outside the U.S.?", "Foreign WC coverage requested?". If the submission email mentions: "Executives travel to Mexico and Canada annually; please include foreign voluntary WC", set Yes. Include country list if available.',
    whereToLook: 'WC supplemental — foreign exposure section, Submission email (travel outside US).',
    inAcord130: 'No',
    whereInAcord130: 'Page 4 "REMARKS (ACORD 101 attached)" — carriers add foreign WC coverage requests here.',
  },
  {
    fieldName: 'managedCareOption',
    category: 'Coverages & Limits',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether employer elects a Managed Care arrangement or Preferred Provider Organization (PPO/MCO) option for WC claims handling and cost containment.',
    extractorLogic: 'Look for supplemental questions: "Participate in managed care or preferred provider program?", "Use of designated medical provider?". If requested explicitly in email ("Please include MCO credits"), set Yes. You can also capture provider names if listed.',
    whereToLook: 'WC supplemental – medical provider / managed care section, Broker email.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'Usually Page 1 or Page 4 under "REMARKS" or in carrier-specific addendums. ACORD 130 itself does not have a standard "Managed Care Option" checkbox but many carriers require it in remarks.',
  },
  // F. PAYROLL & EXPOSURE ATTACHMENTS
  {
    fieldName: 'payrollScheduleAttached',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether any payroll schedule has been provided (Excel, CSV, PDF). This acts as a gating mechanism for populating rating rows.',
    extractorLogic: 'Check submission attachments for: Excel workbook with titles like "Payroll by Class", "Payroll Summary", "Payroll Report", "WC Payroll", "Exposure Worksheet". CSVs with columns for class code, description, payroll. PDFs exported from payroll systems labeled "Annual Payroll Report". If at least one qualifying file exists, set to Yes and store filename(s).',
    whereToLook: 'Attached Excel/CSV/PDF files, Submission email referencing payroll ("See attached payroll by state/class").',
    inAcord130: 'No',
    whereInAcord130: 'N/A (ACORD doesn\'t ask whether it was attached; it simply expects the agent to fill in payroll values.)',
  },
  {
    fieldName: 'payrollByClassAndState',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether the submission includes structured payroll broken out by state and class code, enabling full rating population.',
    extractorLogic: 'Identify a spreadsheet (usually Excel) with columns: State, Class Code, Class Description, Estimated Payroll, Number of Employees. Sometimes: Location #, FT/PT split, Rate, etc. Validate that BOTH state and class code columns exist. Extract each row and map into your classifications[] array (Batch D). If payroll is only provided at total level (not broken down), then set this field to No.',
    whereToLook: 'Payroll Excel (usually main attachment), In occasional cases, payroll is embedded in supplemental as a table.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 – STATE RATING WORKSHEET where all payroll rows must be filled.',
  },
  {
    fieldName: 'overtimePayroll',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Indicates whether the submission contains explicit overtime payroll amounts (used in some states to discount premium base).',
    extractorLogic: 'Search payroll worksheets for columns labeled: "OT Payroll", "Overtime", "OT Hours × OT Rate". If found, extract numeric overtime payroll per class/state. If not found but broker email says "Overtime is significant: ~20% of payroll", capture a narrative-level estimate.',
    whereToLook: 'Payroll Excel, Submission email if referencing heavy overtime.',
    inAcord130: 'No',
    whereInAcord130: 'Could be noted in Page 2 "REMARKS" for rating, but ACORD does not have a standard overtime field.',
  },
  {
    fieldName: 'clericalPayroll',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Indicates whether clerical payroll (usually class code 8810) is provided separately.',
    extractorLogic: 'Check whether payroll Excel contains any rows where classCode = 8810. If so, record the payroll associated with that row(s). If clerical operations are described in supplemental ("5 office clerks"), but no payroll row exists, set clericalPayroll = null but can still create a zero-payroll row for mapping if required downstream.',
    whereToLook: 'Payroll Excel, WC supplemental – description of clerical employees.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 — STATE RATING WORKSHEET row for Class Code 8810.',
  },
  {
    fieldName: 'outsideSalesPayroll',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Indicates whether payroll associated with outside sales employees (e.g., class code 8742) is included.',
    extractorLogic: 'Look for classCode 8742 in payroll Excel. If present, extract payroll and employee counts. If not present but supplemental says "We have 3 outside sales reps," note exposure exists but payroll missing → flag for underwriter.',
    whereToLook: 'Payroll Excel, WC supplemental – "Outside Sales / Travel" section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 2 — STATE RATING WORKSHEET row for Class Code 8742.',
  },
  {
    fieldName: 'subcontractorPayroll',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Represents payroll paid to subcontractors (when they lack WC coverage, this payroll may need to be included for premium).',
    extractorLogic: 'If supplemental indicates any subcontractors without COIs, extract: "Approx $150,000 annual payroll subcontracted without COI", "10% of 5403 work sublet without COI". Add these amounts into classification rows as required or store separately for underwriter review. If supplemental states all subs provide COIs, set to 0 or null.',
    whereToLook: 'WC supplemental – subcontractor section, Submission email (producer notes).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information, Question 7, directing: "Any work sublet without COI? If Yes, payroll for this work must be included in State Rating Worksheet on Page 2."',
  },
  {
    fieldName: 'uninsuredSubcontractorPayroll',
    category: 'Payroll & Exposure Attachments',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Payroll from subcontractors specifically without proof of WC insurance, unlike general subcontractor usage.',
    extractorLogic: 'Identify statements in supplemental such as: "We sometimes use uninsured subcontractors.", "We do not always obtain COIs." Extract numeric amounts or percentages if given. If only % of subcontracted work is uninsured, multiply by subcontracted payroll amount if provided—otherwise store percentage textually.',
    whereToLook: 'WC supplemental – "Sublet without COI" question, Payroll Excel sometimes tags subcontractor payments separately.',
    inAcord130: 'Yes',
    whereInAcord130: 'Same as above (General Information Q7), to be inserted in STATE RATING WORKSHEET as exposure.',
  },
];

async function main() {
  console.log('Starting field definitions update...');

  for (const field of fieldUpdates) {
    try {
      await prisma.fieldDefinition.upsert({
        where: { fieldName: field.fieldName },
        update: {
          category: field.category,
          fieldType: field.fieldType,
          businessDescription: field.businessDescription,
          extractorLogic: field.extractorLogic,
          whereToLook: field.whereToLook,
          inAcord130: field.inAcord130,
          whereInAcord130: field.whereInAcord130,
        },
        create: {
          fieldName: field.fieldName,
          category: field.category,
          fieldType: field.fieldType,
          enteredFieldKey: field.fieldName,
          chatFieldKey: field.fieldName,
          documentFieldKey: field.fieldName,
          businessDescription: field.businessDescription,
          extractorLogic: field.extractorLogic,
          whereToLook: field.whereToLook,
          inAcord130: field.inAcord130,
          whereInAcord130: field.whereInAcord130,
        },
      });
      console.log(`✓ Updated field: ${field.fieldName}`);
    } catch (error) {
      console.error(`✗ Error updating field ${field.fieldName}:`, error);
    }
  }

  console.log('Field definitions update completed!');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
