import { PrismaClient, FieldValueType } from '@prisma/client';

const prisma = new PrismaClient();

// Workers Compensation Field Definitions
// All fields include: businessDescription, extractorLogic, whereToLook, inAcord130, whereInAcord130
const fieldUpdates = [
  // A. SUBMISSION & ADMINISTRATIVE
  {
    fieldName: 'applicantName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Legal name of the business entity seeking workers comp coverage.',
    extractorLogic: 'From the submission email subject and first paragraph, capture the company name in patterns like "WC submission – ABC Manufacturing, Inc.", "Workers comp quote for XYZ Plumbing LLC", "Insured: Smith Roofing Company". If ambiguous, cross-check against payroll reports, loss runs, or prior policy dec pages, which typically show the insured name in a header or "Named Insured" field. When multiple names appear (parent + DBA), choose the one paired with FEIN or "Named Insured" on prior policies; store DBAs separately if needed.',
    whereToLook: 'Submission email (subject + opening lines), broker cover letter, payroll reports, loss runs, prior policy declarations, any attached application/questionnaire.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – top right field labeled "APPLICANT NAME".',
  },
  {
    fieldName: 'mailingAddress',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Primary mailing address for the insured; official correspondence address.',
    extractorLogic: 'Search email and attachments for a full address pattern: street number + street name + city + state abbreviation + ZIP (e.g., "123 Main St, Tacoma, WA 98422"). Prioritize: address under the insured\'s name in broker cover letter or questionnaire, address labeled "Mailing Address" or "Headquarters", address labeled "Named Insured address" on prior policies or loss runs. If multiple addresses (HQ vs. job sites), choose one explicitly tied to the legal entity (not a project site).',
    whereToLook: 'Submission email signature, broker narrative, attached "WC application" PDFs, prior dec pages, loss runs headers, payroll reports.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – in the Applicant block, labeled "MAILING ADDRESS (including ZIP + 4 or Canadian Postal Code)".',
  },
  {
    fieldName: 'officePhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Main business phone number of the insured.',
    extractorLogic: 'Parse the insured/contact info block in attached questionnaires or broker cover letters; look for "Phone", "Tel", or "Office". In the email signature, identify the number closest to the insured\'s contact name, preferring labels like "Office" over "Mobile/Cell". Normalize to E.164 or (XXX) XXX-XXXX while preserving extensions (e.g., x204).',
    whereToLook: 'Submission email signature, any "WC Application" PDF/Word, contact info sections of payroll or HR rosters.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "OFFICE PHONE".',
  },
  {
    fieldName: 'mobilePhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Mobile phone of the primary insured contact.',
    extractorLogic: 'In email signature blocks, capture numbers labeled "Cell", "Mobile", "C:", or that follow the contact\'s name. If multiple numbers exist, heuristically assign the one labeled "C/Mobile" here and another as officePhone. Keep formatting similar to officePhone.',
    whereToLook: 'Submission email signature, any "Contact Sheet" attachment.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "MOBILE PHONE".',
  },
  {
    fieldName: 'website',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Official website of the insured business.',
    extractorLogic: 'Parse email signature and headers in questionnaires for http(s):// or www. links. Exclude social media; pick the primary corporate domain, ideally the same as the applicant email domain. Strip trailing slashes and paths; store root domain where possible.',
    whereToLook: 'Email signature, "About the company" paragraphs in broker submission, any marketing one-pager attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "WEBSITE ADDRESS".',
  },
  {
    fieldName: 'yearsInBusiness',
    category: 'Submission & Administrative',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Number of years the business has operated (under current or predecessor ownership).',
    extractorLogic: 'Look in questionnaires / broker application docs for fields like "Years in business", "Year established", "Business started (YYYY)". If a start year (e.g., 2012) is given, compute years-in-business relative to current policy effective year (but also store the start year separately if you want). If multiple values (e.g., "20 years in construction, 5 years as XYZ LLC"), prefer the current operation under this entity.',
    whereToLook: 'Attached WC app/questionnaire, broker email narrative ("client has been in business for 8 years"), any company profile PDF.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – Applicant section, field labeled "YRS IN BUS".',
  },
  {
    fieldName: 'fein',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Federal Employer Identification Number (9-digit tax ID) for the insured.',
    extractorLogic: 'Scan questionnaires and payroll reports for labels: "FEIN", "Federal Tax ID", "EIN". Use a regex for 9 digits, optionally with a dash (NN-NNNNNNN or NNNNNNNNN). Verify the number appears near the applicantName to avoid grabbing someone else\'s ID (e.g., agent\'s FEIN).',
    whereToLook: 'WC application/forms, payroll summaries, experience mod worksheets, loss runs headers.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – row with "FEDERAL EMPLOYER ID NUMBER".',
  },
  {
    fieldName: 'ncciRiskId',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'NCCI-assigned Risk ID used for experience rating and WC data.',
    extractorLogic: 'In experience rating worksheets (NCCI/WCIRB, usually PDF), find "Risk ID" or "Risk Number" near the top header. Extract the alphanumeric ID exactly as shown. If absent there, check broker\'s submission email for "NCCI Risk ID".',
    whereToLook: 'NCCI/WCIRB experience mod worksheets, broker/actuary loss analysis reports, submission email.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – field labeled "NCCI RISK ID NUMBER".',
  },
  {
    fieldName: 'otherEmployerRegistrationNumber',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Any state or other rating bureau employer registration number (e.g., state unemployment, state employer account number).',
    extractorLogic: 'Search questionnaires and payroll reports for text like "State Employer ID", "UI Account No.", "State Tax ID". Associate the ID with a specific state if indicated. If multiple states are listed, you can store as list of {state, registrationNumber}.',
    whereToLook: 'WC questionnaires, state registration letters attached, payroll summaries.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – field labeled "OTHER RATING BUREAU ID OR STATE EMPLOYER REGISTRATION NUMBER".',
  },
  {
    fieldName: 'submissionType',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Type of transaction requested: quote only, bind/issue, or assigned risk/other special handling.',
    extractorLogic: 'From the email subject/body, detect intent: "Please quote" / "Quote request" → quote, "Please bind", "Bind effective", "Issue policy" → issue, "Assigned risk" or "State fund only" → assigned_risk. If unclear, default to quote for new business, unless the email explicitly mentions renewal binding.',
    whereToLook: 'Submission email subject, first 1–2 paragraphs, any attached "Submission Coversheet".',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "STATUS OF SUBMISSION" section with options "QUOTE", "ISSUE POLICY", "ASSIGNED RISK (attach ACORD 133)".',
  },
  {
    fieldName: 'agencyName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Name of the broker/agency submitting the risk.',
    extractorLogic: 'Use the email sender\'s signature; capture the organization line under their name (e.g., "ABC Insurance Services"). If unclear, parse the sender\'s email domain (@abcinsurance.com) and resolve to a readable form ("ABC Insurance"). If a coversheet or proposal template is attached, use the agency name in its header.',
    whereToLook: 'Email signature, cover letters, broker-branded templates.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – top left block "AGENCY NAME AND ADDRESS".',
  },
  {
    fieldName: 'agencyAddress',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Mailing address of the submitting agency.',
    extractorLogic: 'From the email signature, collect street + city + state + ZIP that appear immediately beneath the agency name. If not in email, check any broker letterhead or PDF footer.',
    whereToLook: 'Email signatures, agency-branded documents.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – in the "AGENCY NAME AND ADDRESS" block.',
  },
  {
    fieldName: 'producerName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Primary producer/agent managing the account at the agency.',
    extractorLogic: 'From the email, take the From: display name and full name in the signature ("Jane Doe, Producer"). If multiple people are CC\'d, pick the one whose title includes "Producer", "AE/Account Executive", or "Broker".',
    whereToLook: 'Email headers, signatures, any "Producer:" line in coversheets.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PRODUCER NAME" in agency info block.',
  },
  {
    fieldName: 'csrName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Account manager/CSR supporting the producer.',
    extractorLogic: 'In email CC list and signatures, look for titles such as "Account Manager", "CSR", "Account Associate". If the sender is clearly the CSR and references "on behalf of [Producer]", record both.',
    whereToLook: 'Email CC + signature, submission coversheet.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "CSR / REPRESENTATIVE NAME".',
  },
  {
    fieldName: 'producerEmail',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Email address of the main producer contact.',
    extractorLogic: 'Use the From: email address of the submission if the sender is the producer; otherwise use the address in the signature line associated with the producer\'s name. Normalize to lowercase.',
    whereToLook: 'Email headers and signature.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'If present, in agency contact fields on Page 1; not always explicitly labeled.',
  },
  {
    fieldName: 'producerPhone',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Direct phone number for producer.',
    extractorLogic: 'In the producer\'s signature, capture the number labeled with their name or labeled "Direct". If only one number is present, it can be used for both officePhone and producerPhone if you want.',
    whereToLook: 'Email signature, broker contact sheets.',
    inAcord130: 'Sometimes',
    whereInAcord130: 'Page 1 agency block if separate phone fields per contact are filled.',
  },
  {
    fieldName: 'underwriterName',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Carrier underwriter the submission is being addressed to (if specified).',
    extractorLogic: 'From the salutation of the email ("Hi Sarah,") when the domain is the carrier and the role is underwriter. Or from phrases like "Attn: John Smith – Senior WC Underwriter". Not required for quoting; treat as optional.',
    whereToLook: 'Email greeting line, any submission coversheet.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "UNDERWRITER" / "COMPANY" section.',
  },
  {
    fieldName: 'agencyCustomerId',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Internal account identifier used in the agency\'s system.',
    extractorLogic: 'Look for codes labeled "Customer ID", "Client Code", "Account Number" on submission coversheets or in email subject lines (e.g., "Client ID 102345 – XYZ Construction"). Capture alphanumeric string; no standard format.',
    whereToLook: 'Coversheet PDFs, subject line, internal account snapshots attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page headers – "AGENCY CUSTOMER ID".',
  },
  {
    fieldName: 'billingPlan',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Whether the account will be agency-billed or direct-billed and any special billing instructions.',
    extractorLogic: 'Search submission cover emails and questionnaires for terms like "direct bill", "agency bill", "bill insured direct", "agency billed". Map text to canonical values agency_bill vs direct_bill. If not specified, leave null; this is often chosen by carrier or broker later.',
    whereToLook: 'Submission email, broker WC application, any "Billing Instructions" attachment.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "BILLING / AUDIT INFORMATION – BILLING PLAN (AGENCY BILL / DIRECT BILL)".',
  },
  {
    fieldName: 'paymentPlan',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Requested installment schedule (annual, quarterly, monthly reporting, etc.).',
    extractorLogic: 'Look for phrases like "quarterly installments", "monthly reporting policy", "annual pay". Map to enumeration: annual, semi_annual, quarterly, monthly, payroll_reporting.',
    whereToLook: 'Submission email, billing instruction pages, broker cover letter.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "PAYMENT PLAN" checkboxes (Annual, Semi-Annual, Quarterly, etc.).',
  },
  {
    fieldName: 'auditType',
    category: 'Submission & Administrative',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'How and when payroll audit is performed (at expiration vs. periodic self-reporting).',
    extractorLogic: 'Search for text like "annual audit", "monthly payroll reporting", "auditable at policy term". Map common phrases to at_expiration, monthly_reporting, semi_annual, etc.',
    whereToLook: 'Submission email, WC appetite/quote request docs, prior policies (audit section).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – "AUDIT (AT EXPIRATION / MONTHLY / SEMI-ANNUAL)".',
  },
  // B. BUSINESS ENTITY & OPERATIONS / GENERAL INFO
  {
    fieldName: 'entityType',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'string' as FieldValueType,
    businessDescription: 'Legal structure of the insured entity (e.g., individual, partnership, corporation, LLC, etc.).',
    extractorLogic: 'Parse the WC supplemental application and broker\'s cover letter for a labeled field like "Entity type", "Business type", or "Legal structure". If not explicitly filled, infer from the legal name: Names ending in "Inc." → corporation, "LLC", "L.L.C." → llc, "LP", "LLP" → partnership variants. Normalize to a small set of enumerated values: individual, partnership, corporation, s_corp, llc, trust, joint_venture, other.',
    whereToLook: 'WC supplemental or "Business information" questionnaire, Broker submission email (intro section), Prior policy dec pages (Named Insured + entity type line).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 1 – row of checkboxes in the Applicant block labeled something like "INDIVIDUAL, PARTNERSHIP, CORPORATION, SUBCHAPTER S CORP, LLC, TRUST, JOINT VENTURE, OTHER".',
  },
  {
    fieldName: 'operationsDescription',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'text' as FieldValueType,
    businessDescription: 'Narrative description of what the business does: services performed, products, customers, and work environment.',
    extractorLogic: 'In WC supplemental and any "Operations" section, extract the full text answer to questions like "Describe your operations in detail", "What does the business do?". If not present or too short, use the submission email body (first 1–3 paragraphs where the broker explains the insured) and pull the contiguous sentences describing operations (e.g., "They operate 4 casual dining restaurants…"). Preserve full paragraph text; do not over-truncate. This field is for LLM context as well as mapping to class codes.',
    whereToLook: 'WC supplemental ("Description of operations"), Broker submission email narrative, Any attached marketing/profile one-pager.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – large narrative box typically labeled "NATURE OF BUSINESS / DESCRIPTION OF OPERATIONS".',
  },
  {
    fieldName: 'hazardousMaterialsExposure',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured\'s past, present, or discontinued operations involve storing, treating, discharging, applying, disposing, or transporting hazardous materials (chemicals, fuels, waste, etc.).',
    extractorLogic: 'In the WC supplemental, look for environmental/risk questions like "Any use, storage, or transport of hazardous materials?", "Any fuel storage tanks, chemicals, or waste handling?". Parse the Yes/No and any narrative description. If not clearly asked in a questionnaire, scan the operationsDescription and any risk engineering reports for keywords: "hazardous", "chemicals", "solvents", "fuel tanks", "waste handling", "hazmat" and infer exposure = Yes if clearly present. Store as a structured object: answer: Yes/No, details: free-text description if provided.',
    whereToLook: 'WC supplemental – "Environmental/hazardous materials" or "General info" section, Risk engineering / safety reports, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 2, typically worded: "DO/HAVE PAST, PRESENT OR DISCONTINUED OPERATIONS INVOLVE STORING, TREATING, DISCHARGING, APPLYING, DISPOSING, OR TRANSPORTING OF HAZARDOUS MATERIALS (e.g., landfills, wastes, fuel tanks, etc.)?" with Yes/No checkboxes and a remarks area.',
  },
  {
    fieldName: 'aircraftOrWatercraftOwned',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured owns, operates, or leases aircraft or watercraft as part of its operations.',
    extractorLogic: 'Look for a general info table in the WC supplemental with questions like "Any owned, leased, or chartered aircraft or watercraft?"; capture Yes/No and explanation. If no explicit question, scan operations and fleet descriptions for words like "plane", "helicopter", "vessel", "boat", "barge", "tug", "charter". Default to No if not mentioned and industry is unlikely to have such exposures (e.g., small restaurant, office-only), but better to leave null if ambiguous.',
    whereToLook: 'WC supplemental – General Information / Exposures section, Fleet or auto schedules (sometimes list watercraft), Broker email if they call out aircraft/watercraft exposures.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 1, usually: "DOES APPLICANT OWN, OPERATE OR LEASE AIRCRAFT/WATERCRAFT?" (Yes/No + explanation).',
  },
  {
    fieldName: 'workUndergroundOrAbove15Feet',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether employees perform work underground or above 15 feet (e.g., trenching, high scaffolding, elevated roofing), which materially changes risk severity.',
    extractorLogic: 'Find questions in the WC supplemental such as "Any work above 15 feet?", "Any underground work or trenching?". Extract Yes/No; parse the explanation field for height ranges and % of work ("framing work up to 20 ft, about 30% of jobs"). If not explicitly asked, scan operationsDescription for terms like "roofing", "scaffolding", "elevated platforms", "trenching", "shoring" and infer high-level yes/no with details.',
    whereToLook: 'WC supplemental – "Operations exposure" or "Work height/underground" questions, Safety/risk questionnaire, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 3: "ANY WORK PERFORMED UNDERGROUND OR ABOVE 15 FEET?" (Yes/No + explanation).',
  },
  {
    fieldName: 'workOverWater',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any work is performed on barges, vessels, docks, piers, or bridges over water.',
    extractorLogic: 'Look for yes/no questions about marine exposures in the WC supplemental ("Any work on or over water?"). If "Yes", extract details such as type of structure (docks, barges), typical duration, % of overall work, and locations. If not asked, search the operations narrative for "dock", "pier", "barge", "marine", "over water", "bridge" and derive.',
    whereToLook: 'WC supplemental – General exposures section, Marine/contractor addenda if present, Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 4: "ANY WORK PERFORMED ON BARGES, VESSELS, DOCKS, BRIDGES OVER WATER?".',
  },
  {
    fieldName: 'subcontractorUsage',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Indicates whether the insured uses subcontractors to perform part of the work.',
    extractorLogic: 'In the WC supplemental, find the line "Subcontractors used?" Yes/No. Capture the Yes/No answer and treat as subcontractorUsage. If no explicit field but operations clearly include subbing (e.g., GC describing subs), infer Yes and capture note in details.',
    whereToLook: 'WC supplemental – "Subcontractor usage" section, Broker email describing operations ("we sub out electrical and plumbing"), Any attached subcontractor procedures/COI language.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 6: "ARE SUB-CONTRACTORS USED? (If \'YES\', give % of work subcontracted)".',
  },
  {
    fieldName: 'subcontractorPercentageSubcontracted',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'number' as FieldValueType,
    businessDescription: 'Approximate percentage of total work or revenue subcontracted to others.',
    extractorLogic: 'Next to the "Subcontractors used?" Yes/No in the WC supplemental, capture numeric values like "20%", "1/3 of work", "about half of field work". Normalize textual fractions into approximate percentages (e.g., "one third" → 33). If no precise figure, infer from narrative if clearly stated ("most specialized trades are subbed out" could be approximated as >50%, or left as null with narrative only).',
    whereToLook: 'WC supplemental – same section as subcontractor usage, Broker email ("~20% of work subbed to licensed trades").',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – same General Information Question 6 remarks line: insurer expects "% of work subcontracted" if "Yes" is checked.',
  },
  {
    fieldName: 'workSubletWithoutCOI',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any work is sublet to subcontractors who do not provide certificates of insurance (COIs) for WC and GL.',
    extractorLogic: 'In the WC supplemental, find questions like "Any work sublet without COIs?" or "Do you always obtain certificates of insurance from subcontractors?". Extract Yes/No and narrative ("Occasionally use small subs without COIs, less than 5% of work"). If the supplement only says "COIs required for all subs", infer workSubletWithoutCOI = No.',
    whereToLook: 'WC supplemental – subcontractor & COI section, Broker email describing subcontractor management.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 7: "ANY WORK SUBLET WITHOUT CERTIFICATES OF INSURANCE? (If \'YES\', payroll for this work must be included in the State Rating Worksheet on Page 2.)".',
  },
  {
    fieldName: 'otherBusinessOperations',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'text' as FieldValueType,
    businessDescription: 'Other types of business activities conducted by the insured beyond the main operations (e.g., retail, manufacturing, distribution side lines).',
    extractorLogic: 'In WC supplemental, look for a question explicitly asking if there are other operations or divisions; capture Yes/No and full explanation. In operationsDescription, detect structure like "In addition to X, they also operate Y…" and capture the "also operate" part as otherBusinessOperations. Store as free text; downstream, it can be used to drive additional class codes.',
    whereToLook: 'WC supplemental – "Other operations / side businesses" question, Operations narrative (broker email or attachment).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 5: "IS APPLICANT ENGAGED IN ANY OTHER TYPE OF BUSINESS?" (with explanation field).',
  },
  {
    fieldName: 'safetyProgramInOperation',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether there is a formal written safety program in place (policies, training, documented procedures).',
    extractorLogic: 'In the WC supplemental safety section, find "Written safety program?" or "Formal safety program?"; capture Yes/No and any notes ("OSHA-compliant written program, updated annually"). If they attach a Safety Manual or reference "see attached safety program", set answer to Yes and note attachments. If completely silent and high-risk industry, leave null instead of assuming No.',
    whereToLook: 'WC supplemental – safety & loss control section, Any attached safety manual or policy summary, Broker cover letter (often highlighting safety program as a positive).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 8: "IS A WRITTEN SAFETY PROGRAM IN OPERATION?".',
  },
  {
    fieldName: 'groupTransportationProvided',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer provides transportation for groups of employees (e.g., vans, buses, crew trucks) to job sites.',
    extractorLogic: 'In the WC supplemental, look for "Do you provide group transportation to employees?" or similar. Extract Yes/No plus description of vehicles and usage if given. Scan operationsDescription for "crew vans", "company shuttle", "transport crews to sites" and infer as needed.',
    whereToLook: 'WC supplemental – transportation or fleet exposures section, Fleet / auto supplement (if attached), Operations narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 9: "ANY GROUP TRANSPORTATION PROVIDED?".',
  },
  {
    fieldName: 'employeesUnder16OrOver60',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any employees are younger than 16 or older than 60, used as a risk screening factor.',
    extractorLogic: 'On the WC supplemental, capture Yes/No to any question about "employees under 16 or over 60". From any employee age distribution reports (if attached), infer yes if extremes are present. Where counts are given ("3 employees over 60"), store them optionally alongside the Yes.',
    whereToLook: 'WC supplemental – employee demographics section, HR/employee summary reports (if included).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 10: "ANY EMPLOYEES UNDER 16 OR OVER 60 YEARS OF AGE?".',
  },
  {
    fieldName: 'seasonalEmployees',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured uses seasonal workers (e.g., during summer, harvest, holiday season).',
    extractorLogic: 'Identify the yes/no question in supplemental for "seasonal employees"; capture answer and, if available, typical season and headcount. If payroll schedules show large seasonal spikes (e.g., Q4 payroll much higher with note "seasonal staff"), mark as Yes and capture the description.',
    whereToLook: 'WC supplemental – employee profile section, Payroll by quarter or seasonal payroll attachments.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 11: "ANY SEASONAL EMPLOYEES?".',
  },
  {
    fieldName: 'volunteerOrDonatedLabor',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Use of workers who are not paid employees but volunteer or provide donated labor.',
    extractorLogic: 'Find the volunteer labor question in the supplemental and capture Yes/No plus description ("church volunteers help staff the thrift store on weekends"). If the insured is a non-profit where volunteers are likely, but the form is silent, leave null (don\'t assume).',
    whereToLook: 'WC supplemental – general info section, Nonprofit-specific supplements, if attached.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 12: "IS THERE ANY VOLUNTEER OR DONATED LABOR? (If \'YES\', please specify)".',
  },
  {
    fieldName: 'employeesWithPhysicalHandicaps',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether any employees with physical handicaps are employed, which may be a consideration for underwriting.',
    extractorLogic: 'Capture Yes/No from the specific question on the WC supplemental; often answered "No". Do not attempt to infer from other data (avoid making assumptions about disabilities).',
    whereToLook: 'WC supplemental – general info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 13: "ANY EMPLOYEES WITH PHYSICAL HANDICAPS?".',
  },
  {
    fieldName: 'employeesTravelOutOfState',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether employees travel outside the main state of operation, including which states and how often.',
    extractorLogic: 'In the supplemental, extract Yes/No and parse the text field for state abbreviations and frequency qualifiers ("OR and ID weekly; CA quarterly"). Where not explicitly listed, search operationsDescription and cover letter for cross-border work ("crews regularly cross from WA into OR"). Store as structured list if possible: [{"state": "OR", "frequency": "weekly"}, ...].',
    whereToLook: 'WC supplemental – travel/out-of-state question, Broker email describing multi-state operations, Payroll by state (corroborate which states have employees).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 14: "DO EMPLOYEES TRAVEL OUT OF STATE? (If \'YES\', indicate state(s) of travel and frequency)".',
  },
  {
    fieldName: 'athleticTeamsSponsored',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer sponsors athletic teams (e.g., company softball or soccer teams), creating incidental WC exposure.',
    extractorLogic: 'Capture Yes/No from a supplemental question on "Athletic teams sponsored?". If Yes, extract name/type of team and whether participants are employees.',
    whereToLook: 'WC supplemental – general info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 15: "ARE ATHLETIC TEAMS SPONSORED?".',
  },
  {
    fieldName: 'preEmploymentPhysicalsRequired',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether physical exams are required after offers of employment are made.',
    extractorLogic: 'From supplemental, read Yes/No on "Pre-employment physicals required?". If details are given ("required for all drivers and warehouse staff"), capture as free text.',
    whereToLook: 'WC supplemental – hiring/HR practices section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 3 – General Information Question 16: "ARE PHYSICALS REQUIRED AFTER OFFERS OF EMPLOYMENT ARE MADE?".',
  },
  {
    fieldName: 'otherInsuranceWithThisInsurer',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured has other policies (e.g., GL, auto, property) with the same carrier considering this WC quote.',
    extractorLogic: 'On the supplemental, look for a question about "Any other policies with this carrier?" or "Do you currently have policies with us?". If the broker email explicitly says "They already place GL and Auto with you", set to Yes and capture lines of business.',
    whereToLook: 'WC supplemental – general info section, Broker cover letter (cross-sell pitch).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 17: "ANY OTHER INSURANCE WITH THIS INSURER?".',
  },
  {
    fieldName: 'priorCoverageDeclinedOrCancelled',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether prior workers comp coverage has been declined, cancelled, or non-renewed within the recent past (usually 3 years).',
    extractorLogic: 'Read Yes/No from the relevant question on the WC supplemental; if Yes, capture full explanation including carrier, date, and reason. If broker email mentions "non-renewed due to loss ratio" or "previous carrier declined renewal", capture that.',
    whereToLook: 'WC supplemental – prior coverage section, Broker email narrative.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 18: "ANY PRIOR COVERAGE DECLINED / CANCELLED / NON-RENEWED IN THE LAST THREE (3) YEARS?" (with state-specific instructions).',
  },
  {
    fieldName: 'employeeHealthPlansProvided',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the employer provides health insurance plans to employees (group medical).',
    extractorLogic: 'On the supplemental, capture Yes/No and any notes on the type of plan ("group health, 70% employer paid"). Do not try to infer from industry; if not mentioned, leave null.',
    whereToLook: 'WC supplemental – benefits/employee info section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 19: "ARE EMPLOYEE HEALTH PLANS PROVIDED?".',
  },
  {
    fieldName: 'leasedEmployees',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured leases employees to or from another entity (PEO or staff leasing arrangement).',
    extractorLogic: 'Find the leased employees question in the supplemental; record Yes/No and any vendor names (e.g., "PEO: Trinet"). If there is a separate PEO/leased employee addendum attached, you can set this to Yes even if the main form says nothing.',
    whereToLook: 'WC supplemental – leased employees/PEO section, Any attached PEO agreement or schedule.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 21: "DO YOU LEASE EMPLOYEES TO OR FROM OTHER EMPLOYERS?".',
  },
  {
    fieldName: 'employeesWorkingAtHome',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether employees predominantly work from home and how many.',
    extractorLogic: 'From the supplemental, capture Yes/No and numeric count if provided ("4 admin employees working remotely"). If no explicit question but an employee roster or org chart indicates remote roles ("Remote account manager"), you can capture approximate counts.',
    whereToLook: 'WC supplemental – general info/employee section, Employee roster (if attached).',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 22: "DO ANY EMPLOYEES PREDOMINANTLY WORK AT HOME? (If \'YES\', # OF EMPLOYEES: ___)".',
  },
  {
    fieldName: 'taxLiensOrBankruptcyLast5Years',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether the insured has had any tax liens or bankruptcy within the last five years.',
    extractorLogic: 'Extract Yes/No from the financial history question in the supplemental. If Yes, capture the narrative including dates, type (tax lien vs bankruptcy), and current status ("Chapter 11 discharged 2023").',
    whereToLook: 'WC supplemental – financial/ownership section.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 23: "ANY TAX LIENS OR BANKRUPTCY WITHIN THE LAST FIVE (5) YEARS? (If \'YES\', please specify)".',
  },
  {
    fieldName: 'unpaidWCPremiumLast5Years',
    category: 'Business Entity & Operations / General Info',
    fieldType: 'boolean' as FieldValueType,
    businessDescription: 'Whether there is any undisputed, unpaid workers comp premium due from the insured or commonly managed/owned enterprises.',
    extractorLogic: 'Read Yes/No from the corresponding question in the WC supplemental. If Yes, extract details: entities, carriers, approximate amounts, and policy numbers.',
    whereToLook: 'WC supplemental – financial/prior premium section, Broker may occasionally mention this in email if it affects placement.',
    inAcord130: 'Yes',
    whereInAcord130: 'Page 4 – General Information Question 24: "ANY UNDISPUTED AND UNPAID WORKERS COMPENSATION PREMIUM DUE FROM YOU OR ANY COMMONLY MANAGED OR OWNED ENTERPRISES? IF YES, EXPLAIN INCLUDING ENTITY NAME(S) AND POLICY NUMBER(S).".',
  },
];

async function main() {
  console.log('Starting field definitions update...');

  for (const field of fieldUpdates) {
    try {
      await prisma.fieldDefinition.upsert({
        where: { fieldName: field.fieldName },
        update: {
          category: field.category,
          fieldType: field.fieldType,
          businessDescription: field.businessDescription,
          extractorLogic: field.extractorLogic,
          whereToLook: field.whereToLook,
          inAcord130: field.inAcord130,
          whereInAcord130: field.whereInAcord130,
        },
        create: {
          fieldName: field.fieldName,
          category: field.category,
          fieldType: field.fieldType,
          enteredFieldKey: field.fieldName,
          chatFieldKey: field.fieldName,
          documentFieldKey: field.fieldName,
          businessDescription: field.businessDescription,
          extractorLogic: field.extractorLogic,
          whereToLook: field.whereToLook,
          inAcord130: field.inAcord130,
          whereInAcord130: field.whereInAcord130,
        },
      });
      console.log(`✓ Updated field: ${field.fieldName}`);
    } catch (error) {
      console.error(`✗ Error updating field ${field.fieldName}:`, error);
    }
  }

  console.log('Field definitions update completed!');
}

main()
  .catch((e) => {
    console.error('Error:', e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
